### ISSUE TITLE
ambiguity in view Distance

### ISSUE THREAD

**Issue by yjavaherian** [SharifAIChallenge/AIC21-Doc#1]
hi.

could you please explain in clearer terms what cells an ant can see when it is at the very bottom of the map?
more precisely, can it see the upper part of the map?
We know that if it moves down it comes up at the upper part of the map, so naturally is should see the upper part when it is at the bottom.

thanks in advance.

**Comment by hamidreza004** [comment]
Salam!

Yes, When an ant is at the bottom of the map, It can see the upper part of the map.
The map is like an infinite world, and like your movements, your vision can cross edges too.
We would change the doc to make this section more clear.

Thanks.
